### ISSUE TITLE
Problem installing nanopy on aarch64

### ISSUE THREAD

**Issue by MikeRow** [npy0/nanopy#9]
It seems like both nanopy and nanolib can't be installed.

Machine: Raspberry PI4 + Ubuntu server 64bit

nanopy requires AMD64 with SSE2
nanolib seems having troubles with -mfpu=neon

![82755162-2b196900-9dd2-11ea-97c1-9a306123e8a3](https://user-images.githubusercontent.com/47996463/84282232-cc761e00-ab39-11ea-9b05-00f354fa18ed.PNG)
![82755164-2c4a9600-9dd2-11ea-99b7-71b0cee48783](https://user-images.githubusercontent.com/47996463/84282235-cda74b00-ab39-11ea-9a9a-b3ddb3fe9e98.PNG)

**Comment by ghost** [comment]
I just pushed the reference implementation of blake2b as fallback. Can you try from the master branch and let me know? I don't have access to a PI to test. Also, if you can help we can try to add the neon version of blake2b as well. I have it implemented locally, but have no way to test.

**Comment by ghost** [comment]
Ok, this might be fixed now. I added arm64 to travis and the job is passing [there](https://travis-ci.com/github/npy0/nanopy/jobs/351176993). Feel free to reopen if it is not fixed #8 .
